language: node_js
node_js:
  - node
services:
  - postgresql

stages:
  - lint
  - test

before_script:
  - psql -c 'create user pooper with password \'vsecure-password\' createdb;'
  - psql -c 'create database wpoops;' -U pooper

jobs:
  include:
    - stage: lint
      script: npm run test
    - stage: test
      script: npm run test
